/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.alex.Boteco.view;

/**
 *
 * @author User
 */
public class HistoricoVendas extends javax.swing.JFrame {

    /**
     * Creates new form HistoricoCliente
     */
    public HistoricoVendas() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabelBuscaCategoria = new javax.swing.JLabel();
        jLabelBuscaCpf = new javax.swing.JLabel();
        jLabelBuscaData = new javax.swing.JLabel();
        jDateChooser = new com.toedter.calendar.JDateChooser();
        jTextFieldBuscaCpf = new javax.swing.JTextField();
        try {
            javax.swing.text.MaskFormatter cpf = 
            new javax.swing.text.MaskFormatter ("###.###.###-##");
            jTextFieldBuscaCpf = new javax.swing.JFormattedTextField(cpf);
        }catch (Exception e){

        }
        jComboBoxCategoria = new javax.swing.JComboBox<>();
        jComboBoxSabor = new javax.swing.JComboBox<>();
        jButtonBuscaCpf = new javax.swing.JButton();
        jButtonBuscaComboBox = new javax.swing.JButton();
        jButtonBuscaData = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jButtonLimpar = new javax.swing.JButton();
        jButtonBuscar = new javax.swing.JButton();
        jButtonVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(20, 20, 20, 20, new java.awt.Color(102, 102, 255)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(7, 7, 7, 7, new java.awt.Color(102, 102, 255)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelBuscaCategoria.setText("Busca por Produto");
        jPanel2.add(jLabelBuscaCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, -1, 20));

        jLabelBuscaCpf.setText("Busca por Cpf");
        jPanel2.add(jLabelBuscaCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 20));

        jLabelBuscaData.setText("Busca por Data");
        jPanel2.add(jLabelBuscaData, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, 20));
        jPanel2.add(jDateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 170, 30));

        jTextFieldBuscaCpf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldBuscaCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBuscaCpfActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldBuscaCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 140, 30));

        jComboBoxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CATEGORIA", "PIZZA", "PASTEL", "EMPADA", "RISOLES" }));
        jPanel2.add(jComboBoxCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, 130, 30));

        jComboBoxSabor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SABOR", "FRANGO", "CARNE", "CALABRESA", "VEGETARIANA" }));
        jPanel2.add(jComboBoxSabor, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 60, 130, 30));

        jButtonBuscaCpf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br.com.alex.Boteco.imagens/lupa.png"))); // NOI18N
        jPanel2.add(jButtonBuscaCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 30, -1));

        jButtonBuscaComboBox.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br.com.alex.Boteco.imagens/lupa.png"))); // NOI18N
        jPanel2.add(jButtonBuscaComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 60, 30, -1));

        jButtonBuscaData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br.com.alex.Boteco.imagens/lupa.png"))); // NOI18N
        jPanel2.add(jButtonBuscaData, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 30, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, 790, 120));

        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(7, 7, 7, 7, new java.awt.Color(102, 102, 255)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 770, 170));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 790, 190));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Gerenciamento de Vendas");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, -1, -1));

        jButtonLimpar.setText("Limpar");
        jPanel1.add(jButtonLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 540, 130, 30));

        jButtonBuscar.setText("Buscar");
        jPanel1.add(jButtonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 540, 130, 30));

        jButtonVoltar.setBackground(new java.awt.Color(153, 153, 255));
        jButtonVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br.com.alex.Boteco.imagens/setaVoltar.png"))); // NOI18N
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 600, 100, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1141, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 716, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1157, 754));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldBuscaCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBuscaCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBuscaCpfActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        MenuAdmin menuAdmin = new MenuAdmin();
        menuAdmin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HistoricoVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HistoricoVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HistoricoVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HistoricoVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HistoricoVendas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscaComboBox;
    private javax.swing.JButton jButtonBuscaCpf;
    private javax.swing.JButton jButtonBuscaData;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JComboBox<String> jComboBoxCategoria;
    private javax.swing.JComboBox<String> jComboBoxSabor;
    private com.toedter.calendar.JDateChooser jDateChooser;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelBuscaCategoria;
    private javax.swing.JLabel jLabelBuscaCpf;
    private javax.swing.JLabel jLabelBuscaData;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextFieldBuscaCpf;
    // End of variables declaration//GEN-END:variables
}
