/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.alex.Boteco.view;

import br.com.alex.Boteco.controller.SalgadoController;
import br.com.alex.Boteco.model.DAO.TableModelSalgado;
import br.com.alex.Boteco.model.SalgadoVO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class TelaEstoque extends javax.swing.JFrame {
    
    TableModelSalgado listaSalgado = new TableModelSalgado();

    /**
     * Creates new form TelaEstoque
     */
    public TelaEstoque() {
        initComponents();
        jTable1.setModel(listaSalgado);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jComboBoxIncluiCategoria = new javax.swing.JComboBox<>();
        jComboBoxIncluiSabor = new javax.swing.JComboBox<>();
        jTextFieldIncluiQtde = new javax.swing.JTextField();
        jLabelIncluiQtde = new javax.swing.JLabel();
        jLabelIncluiValor = new javax.swing.JLabel();
        jTextFieldIncluiValor = new javax.swing.JTextField();
        jButtonIncluir = new javax.swing.JButton();
        jButtonVoltar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jTextFieldAlteraID = new javax.swing.JTextField();
        jLabelAlteraId = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButtonConsultaAlteraIdSalgado = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jButtonExcluir = new javax.swing.JButton();
        jTextFieldExcluiIdSalgado = new javax.swing.JTextField();
        jLabelExcluiIdSalgado = new javax.swing.JLabel();
        jButtonConsultaExcluiSalgado = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jComboBoxConsultaCategoria = new javax.swing.JComboBox<>();
        jComboBoxConsultaSabor = new javax.swing.JComboBox<>();
        jButtonEstoqueTotal = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldConsultaIdSalgado = new javax.swing.JTextField();
        jLabelConsultaIdSalgado = new javax.swing.JLabel();
        jButtonConsultaIdSalgado = new javax.swing.JButton();
        jButtonConsultaComboBox = new javax.swing.JButton();
        jButtonLimpaTabela = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(20, 20, 20, 20, new java.awt.Color(102, 102, 255)));

        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(102, 102, 255)));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(102, 102, 255)));

        jComboBoxIncluiCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CATEGORIA", "PIZZA", "PASTEL", "EMPADA", "RISOLES", " " }));

        jComboBoxIncluiSabor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SABOR", "FRANGO ", "CARNE", "CALABRESA", "VEGETARIANA" }));

        jLabelIncluiQtde.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelIncluiQtde.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelIncluiQtde.setText("Quantidade");

        jLabelIncluiValor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelIncluiValor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelIncluiValor.setText("Valor");

        jButtonIncluir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonIncluir.setText("INCLUIR");
        jButtonIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIncluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jComboBoxIncluiCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(jComboBoxIncluiSabor, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabelIncluiQtde, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldIncluiQtde, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabelIncluiValor, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldIncluiValor, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(jButtonIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxIncluiCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxIncluiSabor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldIncluiQtde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelIncluiQtde)
                    .addComponent(jLabelIncluiValor)
                    .addComponent(jTextFieldIncluiValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonVoltar.setBackground(new java.awt.Color(153, 153, 255));
        jButtonVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br.com.alex.Boteco.imagens/setaVoltar.png"))); // NOI18N
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(102, 102, 255)));

        jLabelAlteraId.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelAlteraId.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelAlteraId.setText("ID");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("ALTERAR");

        jButtonConsultaAlteraIdSalgado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br.com.alex.Boteco.imagens/lupa.png"))); // NOI18N
        jButtonConsultaAlteraIdSalgado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultaAlteraIdSalgadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(jLabelAlteraId, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jTextFieldAlteraID, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonConsultaAlteraIdSalgado, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldAlteraID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelAlteraId))
                        .addGap(3, 3, 3))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonConsultaAlteraIdSalgado, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(102, 102, 255)));

        jButtonExcluir.setBackground(new java.awt.Color(255, 102, 102));
        jButtonExcluir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonExcluir.setText("EXCLUIR");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jLabelExcluiIdSalgado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelExcluiIdSalgado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelExcluiIdSalgado.setText("ID");

        jButtonConsultaExcluiSalgado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br.com.alex.Boteco.imagens/lupa.png"))); // NOI18N
        jButtonConsultaExcluiSalgado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultaExcluiSalgadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelExcluiIdSalgado, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldExcluiIdSalgado, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonConsultaExcluiSalgado, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldExcluiIdSalgado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelExcluiIdSalgado))
                    .addComponent(jButtonConsultaExcluiSalgado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(102, 102, 255)));

        jComboBoxConsultaCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CATEGORIA", "PIZZA", "PASTEL", "EMPADA", "RISOLES", " " }));

        jComboBoxConsultaSabor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SABOR", "FRANGO", "CARNE", "CALABRESA", "VEGETARIANA" }));

        jButtonEstoqueTotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonEstoqueTotal.setText("ESTOQUE TOTAL ");
        jButtonEstoqueTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEstoqueTotalActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Consultas");

        jLabelConsultaIdSalgado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelConsultaIdSalgado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelConsultaIdSalgado.setText("ID");

        jButtonConsultaIdSalgado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br.com.alex.Boteco.imagens/lupa.png"))); // NOI18N
        jButtonConsultaIdSalgado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultaIdSalgadoActionPerformed(evt);
            }
        });

        jButtonConsultaComboBox.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br.com.alex.Boteco.imagens/lupa.png"))); // NOI18N
        jButtonConsultaComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultaComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jComboBoxConsultaCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(jComboBoxConsultaSabor, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonConsultaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelConsultaIdSalgado, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldConsultaIdSalgado, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonConsultaIdSalgado, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110)
                        .addComponent(jButtonEstoqueTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldConsultaIdSalgado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelConsultaIdSalgado)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonConsultaComboBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonEstoqueTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonConsultaIdSalgado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jComboBoxConsultaCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxConsultaSabor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );

        jButtonLimpaTabela.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonLimpaTabela.setText("Limpar Tabela");
        jButtonLimpaTabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpaTabelaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Gerenciamento de Produtos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonVoltar)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonLimpaTabela, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonLimpaTabela)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jButtonVoltar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1139, 730));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        MenuAdmin menuAdmin = new MenuAdmin();
        menuAdmin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jButtonIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIncluirActionPerformed
       
        SalgadoVO salgadoVO = new SalgadoVO();
        SalgadoController salgadoController = new SalgadoController();
        
        salgadoVO.setCategoria(jComboBoxIncluiCategoria.getSelectedItem().toString());
        salgadoVO.setSabor(jComboBoxIncluiSabor.getSelectedItem().toString());
        salgadoVO.setQuantidade(Integer.parseInt(jTextFieldIncluiQtde.getText()));
        salgadoVO.setValor(Double.parseDouble(jTextFieldIncluiValor.getText()));
        boolean retorno = salgadoController.saveSalgado(salgadoVO);
        
        if (retorno) {
            JOptionPane.showMessageDialog(rootPane, "Produto Incluído com sucesso!");
                jComboBoxIncluiCategoria.setSelectedIndex(0);
                jComboBoxIncluiSabor.setSelectedIndex(0);
                jTextFieldIncluiQtde.setText("");
                jTextFieldIncluiValor.setText("");        
                        
        } else {
            JOptionPane.showMessageDialog(rootPane, "Erro! Produto NÃO incluído");            
        }
        
    }//GEN-LAST:event_jButtonIncluirActionPerformed

    private void jButtonEstoqueTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEstoqueTotalActionPerformed
        List<SalgadoVO> lista = new ArrayList<>();
        SalgadoController salgadoController = new SalgadoController();
        lista = salgadoController.findAll();
        
        for (int i= 0; i < lista.size(); i++){
            listaSalgado.addRow(lista.get(i));            
        }
    }//GEN-LAST:event_jButtonEstoqueTotalActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        SalgadoVO salgadoVO = new SalgadoVO();
        SalgadoController salgadoController = new SalgadoController();
        salgadoVO.setIdSalgado(Integer.parseInt(this.jTextFieldExcluiIdSalgado.getText()));
                          
            boolean retorno = salgadoController.deleteSalgado(salgadoVO);
        
            if (retorno) {
                JOptionPane.showMessageDialog(rootPane, "Exclusão Confirmada!");
                this.jTextFieldExcluiIdSalgado.setText("");
                int clearTabela = listaSalgado.getRowCount()-1;
                while(clearTabela != -1){
                    listaSalgado.removeRow(clearTabela);
                    clearTabela--;
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "ERRO! exclusão não confirmada!");
            }       
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonConsultaIdSalgadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultaIdSalgadoActionPerformed
        
        SalgadoVO salgadoVO = new SalgadoVO();
        SalgadoController salgadoController = new SalgadoController();
        salgadoVO.setIdSalgado(Integer.parseInt(jTextFieldConsultaIdSalgado.getText()));
        SalgadoVO buscaId = salgadoController.findById(salgadoVO);
        if (buscaId != null) {           
                listaSalgado.addRow(buscaId); 
                jTextFieldConsultaIdSalgado.setText("");
           } else {
                JOptionPane.showMessageDialog(rootPane, "Produto não encontrado!");
        }
        
    }//GEN-LAST:event_jButtonConsultaIdSalgadoActionPerformed

    private void jButtonConsultaExcluiSalgadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultaExcluiSalgadoActionPerformed
        SalgadoVO salgadoVO = new SalgadoVO();
        SalgadoController salgadoController = new SalgadoController();
        salgadoVO.setIdSalgado(Integer.parseInt(jTextFieldExcluiIdSalgado.getText()));
        SalgadoVO buscaId = salgadoController.findById(salgadoVO);
        if (buscaId != null) {           
                listaSalgado.addRow(buscaId);                            
           } else {
                JOptionPane.showMessageDialog(rootPane, "Produto não encontrado!");
        }
    }//GEN-LAST:event_jButtonConsultaExcluiSalgadoActionPerformed

    private void jButtonLimpaTabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpaTabelaActionPerformed
        
        int clearTabela = listaSalgado.getRowCount()-1;
                while(clearTabela != -1){
                    listaSalgado.removeRow(clearTabela);
                    clearTabela--;
                }

    }//GEN-LAST:event_jButtonLimpaTabelaActionPerformed

    private void jButtonConsultaAlteraIdSalgadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultaAlteraIdSalgadoActionPerformed
        SalgadoVO salgadoVO = new SalgadoVO();
        SalgadoController salgadoController = new SalgadoController();
        salgadoVO.setIdSalgado(Integer.parseInt(jTextFieldExcluiIdSalgado.getText()));
        SalgadoVO buscaId = salgadoController.findById(salgadoVO);
        if (buscaId != null) {           
                listaSalgado.addRow(buscaId);                            
           } else {
                JOptionPane.showMessageDialog(rootPane, "Produto não encontrado!");
        }
    }//GEN-LAST:event_jButtonConsultaAlteraIdSalgadoActionPerformed

    private void jButtonConsultaComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultaComboBoxActionPerformed
        
        int clearTabela = listaSalgado.getRowCount()-1;
                while(clearTabela != -1){
                    listaSalgado.removeRow(clearTabela);
                    clearTabela--;
                }
        
        
        List<SalgadoVO> listaCategoria = new ArrayList<>();
        List<SalgadoVO> listaSabor = new ArrayList<>();
        List<SalgadoVO> listaAmbos = new ArrayList<>();
        SalgadoVO salgadoVO = new SalgadoVO();
        SalgadoController salgadoController = new SalgadoController();        
        
        if (jComboBoxConsultaCategoria.getSelectedItem()!= "CATEGORIA" 
                && jComboBoxConsultaSabor.getSelectedItem() == "SABOR") {
            salgadoVO.setCategoria(jComboBoxConsultaCategoria.getSelectedItem().toString()); 
             listaCategoria = salgadoController.findByCategoria(salgadoVO);
               for (int i = 0; i < listaCategoria.size(); i++) {
                   listaSalgado.addRow(listaCategoria.get(i));                
               }
            }else if(jComboBoxConsultaSabor.getSelectedItem()!= "SABOR" 
                    && jComboBoxConsultaCategoria.getSelectedItem() == "CATEGORIA") {
                   salgadoVO.setSabor(jComboBoxConsultaSabor.getSelectedItem().toString()); 
                    listaSabor = salgadoController.findBySabor(salgadoVO);
                         for (int i = 0; i < listaSabor.size(); i++) {
                            listaSalgado.addRow(listaSabor.get(i));
                         }
            }else if(jComboBoxConsultaCategoria.getSelectedItem()!= "CATEGORIA" 
                    && jComboBoxConsultaSabor.getSelectedItem()!= "SABOR"){
                  salgadoVO.setCategoria(jComboBoxConsultaCategoria.getSelectedItem().toString());
                  salgadoVO.setSabor(jComboBoxConsultaSabor.getSelectedItem().toString());
                   listaAmbos = salgadoController.findByCategoriaSabor(salgadoVO);
                        for (int i = 0; i < listaAmbos.size(); i++) {
                           listaSalgado.addRow(listaAmbos.get(i));
                        }
            }
    }//GEN-LAST:event_jButtonConsultaComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEstoque().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonConsultaAlteraIdSalgado;
    private javax.swing.JButton jButtonConsultaComboBox;
    private javax.swing.JButton jButtonConsultaExcluiSalgado;
    private javax.swing.JButton jButtonConsultaIdSalgado;
    private javax.swing.JButton jButtonEstoqueTotal;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonIncluir;
    private javax.swing.JButton jButtonLimpaTabela;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JComboBox<String> jComboBoxConsultaCategoria;
    private javax.swing.JComboBox<String> jComboBoxConsultaSabor;
    private javax.swing.JComboBox<String> jComboBoxIncluiCategoria;
    private javax.swing.JComboBox<String> jComboBoxIncluiSabor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelAlteraId;
    private javax.swing.JLabel jLabelConsultaIdSalgado;
    private javax.swing.JLabel jLabelExcluiIdSalgado;
    private javax.swing.JLabel jLabelIncluiQtde;
    private javax.swing.JLabel jLabelIncluiValor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldAlteraID;
    private javax.swing.JTextField jTextFieldConsultaIdSalgado;
    private javax.swing.JTextField jTextFieldExcluiIdSalgado;
    private javax.swing.JTextField jTextFieldIncluiQtde;
    private javax.swing.JTextField jTextFieldIncluiValor;
    // End of variables declaration//GEN-END:variables
}
